# Generated by Django 3.1.1 on 2023-11-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_hook_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hook_text',
        ),
    ]
